// SEO page configuration for GroceryLK
// Each entry drives a /p/:slug page with rich content, schema, and internal links.
// IMPORTANT: slugs are permanent URLs — never delete a slug, only add new ones.

export const SEO_PAGES = [
  {
    slug: 'rice-price-sri-lanka',
    query: 'rice',
    name: 'Rice',
    title: 'Rice Price in Sri Lanka Today — Cargills, Kapruka & More',
    desc: 'Compare rice prices in Sri Lanka across Cargills, Kapruka, SPAR, Glomark and Arpico. See live prices for keeri samba, basmati, nadu and more.',
    category: 'rice',
    size: 'per kg',
    body: [
      'Rice is the staple food of Sri Lanka, and prices vary significantly between stores depending on variety, bag size, and whether it is a regulated or market price. GroceryLK compares live rice prices across Cargills, Kapruka, SPAR, Glomark and Arpico so you can see exactly which store offers the best deal today.',
      'Popular local varieties include keeri samba, nadu, samaroo and suduru, while imported basmati and long-grain lines are priced higher. Buying in bulk — 10kg or 25kg bags — almost always works out cheaper per kg than 1kg packs, but not every store lists bulk pricing online.',
      'Rice prices in Sri Lanka are partly regulated by the Consumer Affairs Authority, so large rises are rare, but seasonal supply, harvest cycles (Maha and Yala seasons) and import duties for varieties like basmati can shift prices week to week. Check back daily for the freshest comparison.',
    ],
  },
  {
    slug: 'dhal-price-sri-lanka',
    query: 'dhal',
    name: 'Dhal',
    title: 'Dhal Price in Sri Lanka — Red Dhal (Parippu) Across Stores',
    desc: 'Compare dhal (parippu) prices in Sri Lanka. See live red dhal, green gram and lentil prices at Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'lentils',
    size: 'per pack',
    body: [
      'Dhal (parippu) is a daily cooking staple in Sri Lankan households, used in dhal curry and many accompaniments to rice. GroceryLK compares live red dhal prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Most stores sell red dhal in 500g and 1kg packs, along with green gram (mung), black gram and other lentils. Imported dhal is the most common on shelves and its price is sensitive to global import prices and the LKR exchange rate.',
      'Prices for dhal have been relatively stable compared to fresh produce, but store-level promotions can make a real difference. Use the comparison below to find the cheapest source before you shop.',
    ],
  },
  {
    slug: 'milk-powder-price-sri-lanka',
    query: 'milk powder',
    name: 'Milk Powder',
    title: 'Milk Powder Price in Sri Lanka — Anchor, Ratthi & More',
    desc: 'Compare milk powder prices in Sri Lanka. See live prices for Anchor, Ratthi, Nespray and more brands at Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'dairy',
    size: 'per 400g/1kg',
    body: [
      'Milk powder is one of the most price-sensitive staples in Sri Lanka, with Anchor, Ratthi, Nespray and similar brands making up a large share of household budgets. GroceryLK compares live milk powder prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Sizes range from single-serve sachets (e.g. 25g) to 400g and 1kg tins and refill packs. Larger packs and refill pouches are usually the most economical per gram, but availability varies by store and region.',
      'Imported milk powder prices track global dairy markets and the LKR exchange rate closely, so prices can change within a week. Check the live comparison to lock in the best price before it moves.',
    ],
  },
  {
    slug: 'eggs-price-sri-lanka',
    query: 'eggs',
    name: 'Eggs',
    title: 'Egg Price in Sri Lanka Today — Cheapest Tray by Store',
    desc: 'Compare egg prices in Sri Lanka today. See live tray and box prices at Cargills, Kapruka, SPAR, Glomark & Arpico and find the cheapest store.',
    category: 'dairy',
    size: 'per tray',
    body: [
      'Egg prices in Sri Lanka are among the most searched grocery prices, moving with poultry feed costs, seasonal demand and government price caps. GroceryLK compares live egg prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Eggs are typically sold by the tray (30 eggs) at supermarkets, though smaller boxes of 6 or 10 are common at some stores. Buying by the full tray is almost always the cheapest unit price.',
      'Egg prices can shift sharply, especially around festive seasons like the Sinhala and Tamil New Year. The comparison below reflects current store prices so you know the real cost before you queue.',
    ],
  },
  {
    slug: 'sugar-price-sri-lanka',
    query: 'sugar',
    name: 'Sugar',
    title: 'Sugar Price in Sri Lanka — White & Brown Sugar by Store',
    desc: 'Compare sugar prices in Sri Lanka. See live white and brown sugar prices at Cargills, Kapruka, SPAR, Glomark & Arpico and find the best deal.',
    category: 'staples',
    size: 'per kg',
    body: [
      'Sugar is a tightly tracked staple in Sri Lanka, with prices frequently compared across stores. GroceryLK shows you live sugar prices at Cargills, Kapruka, SPAR, Glomark and Arpico so you can buy where it is cheapest.',
      'Both white sugar and raw/brown sugar are commonly sold in 1kg and larger bags. Prices are partly regulated, but promotion pricing and store competition create real differences.',
      'Check back regularly, as sugar stock availability and pricing can change with import allocations. The live comparison gives you the current picture across all major stores.',
    ],
  },
  {
    slug: 'bread-price-sri-lanka',
    query: 'bread',
    name: 'Bread',
    title: 'Bread Price in Sri Lanka — Sandwich & Whole Wheat by Store',
    desc: 'Compare bread prices in Sri Lanka. See live sandwich bread, whole wheat and loaf prices at Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'bakery',
    size: 'per loaf',
    body: [
      'Bread is a breakfast staple across Sri Lanka, offered in white sandwich, whole wheat and specialty loaves. GroceryLK compares live bread prices at Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Standard white loaves are the cheapest and most widely available, while whole wheat and grain loaves command a premium. Prices are relatively stable but vary between bakers and stores.',
      'Store-baked and branded loaves differ in size and price, so compare the unit value rather than just the pack price. The table below shows current prices across the major supermarket chains.',
    ],
  },
  {
    slug: 'chicken-price-sri-lanka',
    query: 'chicken',
    name: 'Chicken',
    title: 'Chicken Price in Sri Lanka — Fresh & Whole Chicken Across Stores',
    desc: 'Compare chicken prices in Sri Lanka. See live fresh, whole and fillet chicken prices at Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'meat',
    size: 'per kg',
    body: [
      'Chicken is Sri Lanka\u2019s most popular meat, and its price moves noticeably with poultry feed costs and demand. GroceryLK compares live chicken prices at Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Whole chicken, skinless breast fillets, and leg quarters are priced differently per kg, so compare like-for-like cuts. Fresh chicken is usually cheaper than value-added marinated or processed options.',
      'Chicken pricing can change within days. The live comparison below reflects current prices across the major chains so you can get the best per-kg rate.',
    ],
  },
  {
    slug: 'soap-price-sri-lanka',
    query: 'soap',
    name: 'Soap',
    title: 'Soap Price in Sri Lanka — Lux, Lifebuoy & Dettol by Store',
    desc: 'Compare soap and bath bar prices in Sri Lanka. See live prices for Lux, Lifebuoy, Dettol and more at Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'toiletries',
    size: 'per bar',
    body: [
      'Soap and bath bars are daily necessities, with popular brands like Lux, Lifebuoy, Dettol and Sunlight available across all major stores. GroceryLK compares live soap prices at Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Prices depend on brand, bar size and multi-pack deals. Multi-buy packs of 3 or 4 bars usually give the best price per bar, and promotional offers differ between stores.',
      'The comparison below reflects current shelf prices, helping you identify where your regular brand is cheapest this week.',
    ],
  },
  {
    slug: 'biscuits-price-sri-lanka',
    query: 'biscuits',
    name: 'Biscuits',
    title: 'Biscuit Price in Sri Lanka — Maliban, Munchee & More',
    desc: 'Compare biscuit prices in Sri Lanka. See live prices for Maliban, Munchee and other brands at Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'snacks',
    size: 'per pack',
    body: [
      'Biscuits are a huge category in Sri Lanka, led by home-grown brands Maliban and Munchee alongside imported options. GroceryLK compares live biscuit prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Prices vary by pack size, with family packs and multi-packs offering better value per unit. Cream biscuits, cookies, and crackers occupy different price tiers.',
      'Biscuit promotions rotate frequently between stores. Check the live comparison to spot the current best-value packs.',
    ],
  },
  {
    slug: 'tea-price-sri-lanka',
    query: 'tea',
    name: 'Tea',
    title: 'Tea Price in Sri Lanka — Dilmah, Lipton & Ceylon Tea by Store',
    desc: 'Compare tea prices in Sri Lanka. See live prices for Dilmah, Lipton, Zesta and Ceylon tea at Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'beverages',
    size: 'per pack',
    body: [
      'Tea is synonymous with Sri Lanka, and the country\u2019s Ceylon tea brands — Dilmah, Lipton, Zesta — are available across every major supermarket. GroceryLK compares live tea prices at Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Bulk tea bags and loose-leaf packets vary widely in price by quality grade and pack size. Larger boxed tea bags usually deliver the best value per cup.',
      'Tea prices are fairly stable, but promotional packs rotate. The comparison below helps you find the best deal on your preferred brand.',
    ],
  },
  {
    slug: 'cooking-oil-price-sri-lanka',
    query: 'cooking oil',
    name: 'Cooking Oil',
    title: 'Cooking Oil Price in Sri Lanka — Coconut, Vegetable & More',
    desc: 'Compare cooking oil prices in Sri Lanka. See live coconut oil, vegetable oil and olive oil prices at Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'staples',
    size: 'per L',
    body: [
      'Cooking oil is a price-sensitive kitchen staple in Sri Lanka, spanning coconut oil, vegetable oil, sunflower oil and olive oil. GroceryLK compares live prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Coconut oil is the traditional and most expensive option, while vegetable and sunflower oils offer cheaper alternatives. Prices are quoted per litre and larger packs (2L, 5L) are usually more economical.',
      'Vegetable oil prices track global edible-oil markets and are among the most volatile pantry items. Check back for current prices before restocking.',
    ],
  },
  {
    slug: 'noodles-price-sri-lanka',
    query: 'noodles',
    name: 'Noodles',
    title: 'Noodles Price in Sri Lanka — Maggi, Prima & Koka by Store',
    desc: 'Compare noodle prices in Sri Lanka. See live prices for Maggi, Prima, Koka and instant noodles at Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'snacks',
    size: 'per pack',
    body: [
      'Instant noodles are a quick-meal staple in Sri Lanka, dominated by Prima, Maggi and Koka. GroceryLK compares live noodle prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Prices depend on the flavour, pack weight, and whether you buy single, multi-pack, or family packs. Multi-packs give the best per-unit value.',
      'Promotions on noodles rotate often across stores. Use the comparison below to find the current best price on your preferred flavour.',
    ],
  },
  {
    slug: 'yogurt-price-sri-lanka',
    query: 'yogurt',
    name: 'Yogurt',
    title: 'Yogurt Price in Sri Lanka — Set & Drinking Yogurt by Store',
    desc: 'Compare yogurt and curd prices in Sri Lanka. See live set yogurt, drinking yogurt and curd prices at Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'dairy',
    size: 'per cup',
    body: [
      'Yogurt and curd are everyday dairy items in Sri Lanka, sold as set cups, drinking yogurt and traditional curd pots. GroceryLK compares live yogurt prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Set yogurt cups and drinking yogurts are priced per unit with multi-pack bundles common. Larger family pots generally give the best value per millilitre.',
      'Yogurt prices are fairly stable but promotional bundles fluctuate. Compare across stores to find the cheapest per-cup price.',
    ],
  },
  {
    slug: 'fish-price-sri-lanka',
    query: 'fish',
    name: 'Fish',
    title: 'Fish Price in Sri Lanka — Fresh & Canned by Store',
    desc: 'Compare fish and seafood prices in Sri Lanka. See live fresh fish, canned fish and frozen seafood prices at Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'meat',
    size: 'per kg',
    body: [
      'Fish is a staple source of protein in Sri Lanka, spanning fresh fish, canned tuna and frozen seafood. GroceryLK compares live fish prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Fresh fish is priced per kilogram and varies daily with the catch, while canned fish follows import pricing. Frozen seafood sits between the two in volatility.',
      'Compare like-for-like (fresh vs canned vs frozen) to get the best value on your preferred seafood.',
    ],
  },
  {
    slug: 'battery-price-sri-lanka',
    query: 'battery',
    name: 'Batteries',
    title: 'Battery Price in Sri Lanka — AA, AAA & Rechargeable',
    desc: 'Compare battery prices in Sri Lanka. See live AA, AAA and rechargeable battery prices from Eveready, Duracell and more at major stores.',
    category: 'household',
    size: 'per pack',
    body: [
      'Batteries for remotes, torches and gadgets are a recurring household purchase in Sri Lanka. GroceryLK compares live battery prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Battery packs (2, 4 or 8 pieces) are priced per pack, and buying in bulk is more economical. Rechargeable sets cost more upfront but pay off over time.',
      'Compare per-battery prices rather than pack price to find the best deal.',
    ],
  },
  {
    slug: 'shampoo-price-sri-lanka',
    query: 'shampoo',
    name: 'Shampoo',
    title: 'Shampoo Price in Sri Lanka — Sunsilk, Pantene & Dove',
    desc: 'Compare shampoo prices in Sri Lanka. Find Sunsilk, Pantene, Dove and Head & Shoulders at the best price across Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'toiletries',
    size: 'per bottle',
    body: [
      'Shampoo is another price-sensitive toiletries category in Sri Lanka, with Sunsilk, Pantene, Dove and Head & Shoulders dominating shelves. GroceryLK compares live shampoo prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Bottle sizes range from sachets to 1L refill packs, with larger and refill formats offering better value per ml.',
      'Shampoo promotions rotate frequently between stores, so the live comparison helps you buy your brand at the best price.',
    ],
  },
  {
    slug: 'toothpaste-price-sri-lanka',
    query: 'toothpaste',
    name: 'Toothpaste',
    title: 'Toothpaste Price in Sri Lanka — Colgate, Pepsodent & More',
    desc: 'Compare toothpaste prices in Sri Lanka. See live prices for Colgate, Pepsodent, Sensodyne and more at Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'toiletries',
    size: 'per tube',
    body: [
      'Toothpaste is a daily necessity with a wide price range by brand and size. GroceryLK compares live toothpaste prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Family-size tubes and multi-packs offer the best value per gram, while premium brands like Sensodyne cost more.',
      'Compare per-gram prices across stores to choose wisely, as brand prices differ noticeably by retailer.',
    ],
  },
  {
    slug: 'masala-price-sri-lanka',
    query: 'masala',
    name: 'Masala & Spices',
    title: 'Masala & Spice Price in Sri Lanka — Curry & Chilli Powder',
    desc: 'Compare masala and spice prices in Sri Lanka. Find curry powder, chilli powder, turmeric and more at Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'spices',
    size: 'per pack',
    body: [
      'Masala and spice mixes are essential to Sri Lankan cooking. GroceryLK compares live masala and spice prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Curry powder, chilli powder, turmeric and roasted curry powder are the most-bought, priced per pack or per kilogram.',
      'Spice prices are sensitive to import and harvest supply, so prices can shift. Compare before you buy your monthly restock.',
    ],
  },
  {
    slug: 'jam-price-sri-lanka',
    query: 'jam',
    name: 'Jam',
    title: 'Jam Price in Sri Lanka — Fruit Jam & Marmalade by Store',
    desc: 'Compare jam prices in Sri Lanka. See live fruit jam, marmalade and spread prices at Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'snacks',
    size: 'per jar',
    body: [
      'Jams and fruit spreads are a common breakfast and snack item. GroceryLK compares live jam prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Jars range from small single-serve to large 500g+ formats, with bigger jars usually cheaper per gram.',
      'Brand and fruit variety affect price, and promotions vary by store. Compare to find the best value.',
    ],
  },
  {
    slug: 'sauce-price-sri-lanka',
    query: 'sauce',
    name: 'Sauce',
    title: 'Sauce Price in Sri Lanka — Ketchup, Chilli & Soya Sauce',
    desc: 'Compare sauce prices across Sri Lankan stores. Find ketchup, chilli sauce, soya sauce and more at Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'staples',
    size: 'per bottle',
    body: [
      'Ketchup, chilli sauce and soya sauce are cooking and table staples in Sri Lanka. GroceryLK compares live sauce prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Bottle sizes and brands vary, with larger bottles and value packs offering better per-millilitre prices.',
      'Sauce pricing is stable but promotional bundles rotate across stores — compare before restocking.',
    ],
  },
  {
    slug: 'ice-cream-price-sri-lanka',
    query: 'ice cream',
    name: 'Ice Cream',
    title: 'Ice Cream Price in Sri Lanka — Tubs, Cones & Popsicles',
    desc: 'Compare ice cream prices in Sri Lanka. Find ice cream tubs, cones and popsicles across Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'snacks',
    size: 'per tub',
    body: [
      'Ice cream is a popular treat with a loyal following for local brands. GroceryLK compares live ice cream prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Litre tubs, family packs and individual cones and sticks are all commonly sold, with tubs giving the best value per ml.',
      'Promotions on ice cream are seasonal and frequent — check the comparison for the current best deal.',
    ],
  },
  {
    slug: 'toilet-paper-price-sri-lanka',
    query: 'toilet paper',
    name: 'Toilet Paper',
    title: 'Toilet Paper Price in Sri Lanka — Rolls & Jumbo Packs',
    desc: 'Compare toilet paper and tissue prices in Sri Lanka. Find rolls, packs and jumbo rolls at Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'household',
    size: 'per pack',
    body: [
      'Toilet paper and tissue are regular household purchases in Sri Lanka. GroceryLK compares live prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Single, twin, and multi-roll value packs are common; jumbo packs usually give the best per-roll price.',
      'Compare per-roll prices because ply and roll length vary between brands.',
    ],
  },
  {
    slug: 'detergent-price-sri-lanka',
    query: 'detergent',
    name: 'Detergent',
    title: 'Detergent Price in Sri Lanka — Ariel, Surf & Washing Powder',
    desc: 'Compare laundry detergent prices in Sri Lanka. Find Ariel, Surf Excel and washing powder across Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'household',
    size: 'per pack',
    body: [
      'Laundry detergent is a must-buy household item, spanning powder, liquid and laundry bars. GroceryLK compares live detergent prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Washing powder by weight is the most-sold form, and larger packs (1kg+) give the best value per wash.',
      'Detergent promotions rotate frequently. Compare per-kg prices to find the best deal on your preferred brand.',
    ],
  },
  {
    slug: 'water-price-sri-lanka',
    query: 'water bottles',
    name: 'Water Bottles',
    title: 'Bottled Water Price in Sri Lanka — 1L & 1.5L by Store',
    desc: 'Compare bottled water prices in Sri Lanka. Find 1L and 1.5L bottles across Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'beverages',
    size: 'per bottle',
    body: [
      'Bottled water is an everyday purchase in Sri Lanka. GroceryLK compares live bottled water prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'The most common sizes are 1L and 1.5L bottles; cartons of 6 or 12 bottles give the best per-bottle price.',
      'Water pricing is competitive, so per-litre comparison matters. Use the table to find the cheapest bottle.',
    ],
  },
  {
    slug: 'baby-diapers-price-sri-lanka',
    query: 'diapers',
    name: 'Baby Diapers',
    title: 'Baby Diaper Price in Sri Lanka — Pampers & Huggies',
    desc: 'Compare diaper prices in Sri Lanka. Find Pampers, Huggies and baby wipes at the best price across Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'baby',
    size: 'per pack',
    body: [
      'Baby diapers are a significant recurring cost for parents in Sri Lanka. GroceryLK compares live diaper prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Diapers are priced per pack of 20–60, and jumbo packs and multi-buys slash the per-diaper cost.',
      'Per-diaper price is what matters — compare across stores to cut a meaningful monthly expense.',
    ],
  },
  {
    slug: 'cereal-price-sri-lanka',
    query: 'cereal',
    name: 'Breakfast Cereal',
    title: 'Breakfast Cereal Price in Sri Lanka — Corn Flakes & Oats',
    desc: 'Compare breakfast cereal prices in Sri Lanka. Find Corn Flakes, oats, granola and muesli across Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'snacks',
    size: 'per box',
    body: [
      'Breakfast cereal and oats are morning staples for many Sri Lankan households. GroceryLK compares live cereal prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Boxes range from 300g to 1kg, with family sizes giving the best per-gram value. Oats are often cheaper than branded corn flakes.',
      'Compare per-100g prices to weigh value across brands.',
    ],
  },
  {
    slug: 'ketchup-price-sri-lanka',
    query: 'ketchup',
    name: 'Ketchup',
    title: 'Ketchup Price in Sri Lanka — Maggi, Del Monte & Heinz',
    desc: 'Compare ketchup and tomato sauce prices in Sri Lanka. Find Maggi, Del Monte and Heinz across Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'staples',
    size: 'per bottle',
    body: [
      'Ketchup and tomato sauce are common table condiments in Sri Lanka. GroceryLK compares live ketchup prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Bottle sizes and brands vary, with squeezy bottles and family sizes the most economical per millilitre.',
      'Promotions on ketchup are frequent — compare per-bottle prices before you buy.',
    ],
  },
  {
    slug: 'cheese-price-sri-lanka',
    query: 'cheese',
    name: 'Cheese',
    title: 'Cheese Price in Sri Lanka — Cheddar, Slices & Processed',
    desc: 'Compare cheese prices in Sri Lanka. Find cheddar, processed cheese, mozzarella and slices across Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'dairy',
    size: 'per pack',
    body: [
      'Cheese is a premium dairy item in Sri Lanka, spanning cheddar blocks, slices and processed spreads. GroceryLK compares live cheese prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Processed slices and cheese spreads are cheapest, while fresh cheddar and mozzarella cost more. Pack sizes from 140g to 1kg are sold.',
      'Compare per-100g prices to get the best value, as formats differ a lot between brands.',
    ],
  },
  {
    slug: 'sambol-price-sri-lanka',
    query: 'sambol',
    name: 'Sambol',
    title: 'Sambol Price in Sri Lanka — Seeni Sambol & Pol Sambol',
    desc: 'Compare sambol and seeni sambol prices in Sri Lanka. Find coconut sambol, Maldives fish sambol and chilli paste across stores.',
    category: 'spices',
    size: 'per pack',
    body: [
      'Sambol mixes — seeni sambol, pol sambol and Maldives fish sambol — are Sri Lankan pantry essentials. GroceryLK compares live sambol prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Ready-to-cook sambol packets and jarred products are available; jars are more convenient but often pricier per gram.',
      'Compare across stores to find the best deal on your regular sambol.',
    ],
  },
  {
    slug: 'soya-meat-price-sri-lanka',
    query: 'soya meat',
    name: 'Soya Meat',
    title: 'Soya Meat Price in Sri Lanka — Chunks, Mince & Nuggets',
    desc: 'Compare soya meat and TVP prices in Sri Lanka. Find soya chunks, mince and nuggets across Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'staples',
    size: 'per pack',
    body: [
      'Soya meat (textured vegetable protein) is a popular affordable protein in Sri Lanka. GroceryLK compares live soya meat prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Soya chunks, mince and nuggets are sold in bags of 250g to 1kg, with bigger bags giving the best per-kg price.',
      'Soya meat is price-competitive and stable compared to fresh protein — compare to find the best per-kg rate.',
    ],
  },
  {
    slug: 'toothbrush-price-sri-lanka',
    query: 'toothbrush',
    name: 'Toothbrush',
    title: 'Toothbrush Price in Sri Lanka — Oral-B, Colgate & More',
    desc: 'Compare toothbrush prices in Sri Lanka. Find Oral-B, Colgate and electric toothbrushes across Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'toiletries',
    size: 'per brush',
    body: [
      'Toothbrushes are a regular household replacement item. GroceryLK compares live toothbrush prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Multi-packs (2–4 brushes) offer the best value per brush, while electric toothbrushes are a bigger one-time purchase.',
      'Compare per-brush prices to save on a recurring buy.',
    ],
  },
  {
    slug: 'dilmah-tea-price-sri-lanka',
    query: 'dilmah',
    name: 'Dilmah Tea',
    title: 'Dilmah Tea Price in Sri Lanka — Ceylon Tea Bags & Green Tea',
    desc: 'Compare Dilmah tea prices in Sri Lanka. Find Dilmah Ceylon tea bags, green tea and premium boxes across Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'beverages',
    size: 'per box',
    body: [
      'Dilmah is Sri Lanka\u2019s most famous tea brand. GroceryLK compares live Dilmah prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Dilmah sells tea bags in boxes of 25 to 200, plus loose-leaf and specialty green teas. Larger boxes give the best per-bag price.',
      'Dilmah pricing is stable but pack promotions vary by store. Compare per-bag to find the best value.',
    ],
  },
  {
    slug: 'kiribath-price-sri-lanka',
    query: 'kiribath',
    name: 'Kiribath Ingredients',
    title: 'Kiribath Ingredient Prices in Sri Lanka — Rice & Coconut Milk',
    desc: 'Compare kiribath and milk rice ingredient prices in Sri Lanka. Find rice, coconut milk and more across Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'rice',
    size: 'per pack',
    body: [
      'Kiribath (milk rice) is a cherished Sri Lankan dish served on special occasions. GroceryLK compares live prices for its ingredients — rice and coconut milk — across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Short-grain rice and coconut milk are the core ingredients, with prices per pack. Compare both to plan an economical festive meal.',
      'Check back around festive seasons when kiribath demand and prices peak.',
    ],
  },
  {
    slug: 'coconut-price-sri-lanka',
    query: 'coconut',
    name: 'Coconut',
    title: 'Coconut Price in Sri Lanka — Fresh & Coconut Milk by Store',
    desc: 'Compare coconut prices in Sri Lanka. See live fresh coconut and coconut milk prices at Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'staples',
    size: 'per coconut',
    body: [
      'Coconut is central to Sri Lankan cooking, used fresh or as coconut milk. GroceryLK compares live coconut prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Fresh coconuts are priced per nut, while coconut milk comes in cartons and tins. Fresh prices are volatile and closely watched by households.',
      'Coconut prices trend up in dry seasons and around festive periods. The live comparison shows current retail prices across the major chains.',
    ],
  },
  {
    slug: 'chilli-price-sri-lanka',
    query: 'chilli',
    name: 'Chilli',
    title: 'Chilli Price in Sri Lanka — Chilli Powder & Fresh by Store',
    desc: 'Compare chilli prices in Sri Lanka. See live chilli powder and fresh green chilli prices at Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'spices',
    size: 'per pack',
    body: [
      'Chilli is a non-negotiable ingredient in Sri Lankan cooking, available as fresh green chilli, dried chilli, and chilli powder. GroceryLK compares live prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Chilli powder is sold by the pack, while fresh green chilli is priced per kilogram and is highly volatile.',
      'Chilli powder price is sensitive to import costs, while fresh chilli follows local supply. Compare live prices before shopping.',
    ],
  },
  {
    slug: 'salt-price-sri-lanka',
    query: 'salt',
    name: 'Salt',
    title: 'Salt Price in Sri Lanka — Table, Sea & Rock Salt',
    desc: 'Compare salt prices in Sri Lanka. Find table salt, sea salt and rock salt across Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'staples',
    size: 'per pack',
    body: [
      'Salt is a daily cooking necessity sold in iodised, sea and rock forms. GroceryLK compares live salt prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Pack sizes range from 500g to 2kg, with larger packs offering the best value per kg.',
      'Salt pricing is generally stable and cheap, but compare to stock up at the best rate.',
    ],
  },
  {
    slug: 'face-cream-price-sri-lanka',
    query: 'face cream',
    name: 'Face Cream',
    title: 'Face Cream Price in Sri Lanka — Nivea, Olay & Ponds',
    desc: 'Compare face cream and moisturizer prices in Sri Lanka. Find Nivea, Olay, Ponds and more across Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'toiletries',
    size: 'per jar',
    body: [
      'Face creams and moisturizers are regular personal-care purchases. GroceryLK compares live face cream prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Jars and tubes range from travel sizes to family jars, with larger formats cheaper per gram.',
      'Beauty promotions vary widely by store — compare to buy your brand at the best price.',
    ],
  },
  {
    slug: 'washing-powder-price-sri-lanka',
    query: 'washing powder',
    name: 'Washing Powder',
    title: 'Washing Powder Price in Sri Lanka — Compare Detergent Brands',
    desc: 'Compare washing powder prices in Sri Lanka. Find laundry detergent, stain remover and fabric softener across Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'household',
    size: 'per pack',
    body: [
      'Washing powder is a staple household purchase in Sri Lanka. GroceryLK compares live washing powder prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Powder, liquid and bar formats are sold; powder packs from 400g to 2kg are most common, with bigger packs better per kg.',
      'Per-kg comparison reveals real savings across brands and stores.',
    ],
  },
  {
    slug: 'candle-price-sri-lanka',
    query: 'candle',
    name: 'Candles',
    title: 'Candle Price in Sri Lanka — Pillars, Tealights & Emergency',
    desc: 'Compare candle prices in Sri Lanka. Find scented candles, tea lights and emergency candles across Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'household',
    size: 'per pack',
    body: [
      'Candles are needed for emergencies and ambience in Sri Lanka. GroceryLK compares live candle prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Emergency candle packs, tea lights and scented jar candles occupy different price tiers; multi-packs are cheapest.',
      'Compare per-piece prices to find the best value on a regular household buy.',
    ],
  },
  {
    slug: 'tuna-price-sri-lanka',
    query: 'tuna',
    name: 'Canned Tuna',
    title: 'Tuna Price in Sri Lanka — Canned Tuna in Oil & Brine',
    desc: 'Compare canned tuna prices in Sri Lanka. Find tuna in oil, brine and flavored tuna across Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'meat',
    size: 'per can',
    body: [
      'Canned tuna is a convenient, widely-eaten protein in Sri Lanka. GroceryLK compares live tuna prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Tuna in oil and brine, plus flavored variants, come in standard 185g cans and larger 400g tins, with bigger cans cheaper per gram.',
      'Canned tuna promotions are frequent — compare per-can prices to stock up cheaply.',
    ],
  },
  {
    slug: 'fruit-juice-price-sri-lanka',
    query: 'fruit juice',
    name: 'Fruit Juice',
    title: 'Fruit Juice Price in Sri Lanka — Orange, Mango & Cartons',
    desc: 'Compare fruit juice prices in Sri Lanka. Find orange juice, mango juice and mixed fruit juice cartons across Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'beverages',
    size: 'per carton',
    body: [
      'Fruit juices are a popular beverage category in Sri Lanka. GroceryLK compares live fruit juice prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Cartons, bottles and family packs range from 200ml to 1L, with larger formats better value per ml.',
      'Compare per-100ml prices, as juice brands differ widely across pack formats.',
    ],
  },
  {
    slug: 'potato-price-sri-lanka',
    query: 'potato',
    name: 'Potato',
    title: 'Potato Price in Sri Lanka — Per 1kg by Store',
    desc: 'Compare potato prices in Sri Lanka. See live 1kg potato prices at Cargills, Kapruka, SPAR, Glomark & Arpico and find the cheapest store today.',
    category: 'vegetables',
    size: 'per 1kg',
    body: [
      'Potato is a daily vegetable staple in Sri Lanka and one of the most price-volatile items in the fresh produce aisle. GroceryLK compares live potato prices per 1kg across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Most supermarkets price potatoes per kilogram, whether loose or in netted 1kg packs. Prices swing with import supply, harvest cycles and seasonal rainfall.',
      'Fresh produce prices change frequently, sometimes daily. The comparison below reflects current store prices so you buy at the right moment.',
    ],
  },
  {
    slug: 'tomato-price-sri-lanka',
    query: 'tomato',
    name: 'Tomato',
    title: 'Tomato Price in Sri Lanka — Per 1kg by Store',
    desc: 'Compare tomato prices in Sri Lanka. See live 1kg tomato prices at Cargills, Kapruka, SPAR, Glomark & Arpico and find the cheapest store today.',
    category: 'vegetables',
    size: 'per 1kg',
    body: [
      'Tomatoes are a price-sensitive fresh vegetable in Sri Lanka, with retail prices fluctuating sharply with supply. GroceryLK compares live tomato prices per 1kg across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Prices are per kilogram and can vary between loose and pre-packed tomatoes at the same store. Supply-driven swings are common during wet seasons.',
      'Because tomato prices move fast, the live comparison helps you see the current price before heading to the market or ordering online.',
    ],
  },
  {
    slug: 'onion-price-sri-lanka',
    query: 'onion',
    name: 'Onion',
    title: 'Onion Price in Sri Lanka — Big & Red Onion by Store',
    desc: 'Compare onion prices in Sri Lanka. See live big onion and red onion prices at Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'vegetables',
    size: 'per kg',
    body: [
      'Onions — both the large white "big onion" and the smaller red shallots — are essential to Sri Lankan cooking. GroceryLK compares live onion prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Big onions and red onions are priced separately per kilogram, and both are among the more volatile fresh prices, sensitive to import levels and harvests.',
      'Check the live comparison to see which store is cheapest for onions today, as prices can swing noticeably week to week.',
    ],
  },
  {
    slug: 'dhal-red-price-sri-lanka',
    query: 'red dhal',
    name: 'Red Dhal',
    title: 'Red Dhal Price in Sri Lanka — Per 500g & 1kg by Store',
    desc: 'Compare red dhal (parippu) prices in Sri Lanka. See live 500g and 1kg prices at Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'lentils',
    size: 'per 500g',
    body: [
      'Red dhal, known locally as "parippu" or "mysore dhal", is the most widely used lentil in Sri Lankan kitchens. GroceryLK compares live red dhal prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Red dhal is typically sold in 500g and 1kg packs. Prices depend on origin (imported or local) and brand.',
      'Compare the per-unit price across stores to buy the same dhal for less, as brand and pack promotions vary.',
    ],
  },
  {
    slug: 'rani-milk-powder-price-sri-lanka',
    query: 'rani milk powder',
    name: 'Rani Milk Powder',
    title: 'Rani Milk Powder Price in Sri Lanka — Across All Stores',
    desc: 'Compare Rani milk powder prices in Sri Lanka. See live prices at Cargills, Kapruka, SPAR, Glomark & Arpico and find where it is cheapest.',
    category: 'dairy',
    size: 'per 400g',
    body: [
      'Rani milk powder is a widely-used everyday brand in Sri Lanka, valued for its affordability. GroceryLK compares live Rani prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Rani is commonly sold in 400g pouches, with larger packs offering better value per gram.',
      'Rani pricing is among the most price-compared in the category, so the live comparison helps you buy it at the best available rate.',
    ],
  },
  {
    slug: 'anchor-milk-powder-price-sri-lanka',
    query: 'anchor milk powder',
    name: 'Anchor Milk Powder',
    title: 'Anchor Milk Powder Price in Sri Lanka — 1kg & 400g by Store',
    desc: 'Compare Anchor milk powder prices in Sri Lanka. See live 1kg and 400g prices at Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'dairy',
    size: 'per 1kg',
    body: [
      'Anchor milk powder is a premium everyday brand in Sri Lanka. GroceryLK compares live Anchor prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Anchor is sold in 400g tins, refill pouches and larger 1kg formats, with refills generally cheaper per gram than tins.',
      'Anchor is price-sensitive and promotional offers rotate. Use the comparison to find the current best price on your usual size.',
    ],
  },
  {
    slug: 'keells-products-price-sri-lanka',
    query: 'keells',
    name: 'Keells Products',
    title: 'Keells Product Prices in Sri Lanka — Compare Across Stores',
    desc: 'Compare Keells brand product prices in Sri Lanka across Cargills, Kapruka, SPAR, Glomark & Arpico. See live prices for dhal, rice and more.',
    category: 'staples',
    size: 'various',
    body: [
      'Keells is one of Sri Lanka\u2019s best-known local food brands, spanning rice, dhal, spices, canned goods and more. GroceryLK compares live Keells product prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Keells products are competitively priced local staples, often used in daily cooking. Prices vary by format and pack size.',
      'Compare across stores to get the best price on your regular Keells items.',
    ],
  },
  {
    slug: 'chocolate-price-sri-lanka',
    query: 'chocolate',
    name: 'Chocolate',
    title: 'Chocolate Price in Sri Lanka — Candyland, Nestle & Imported',
    desc: 'Compare chocolate prices in Sri Lanka. Find Candyland, Nestle, Cadbury and imported chocolate across Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'snacks',
    size: 'per bar',
    body: [
      'Chocolate is a staple treat across Sri Lanka, led by Candyland and imported brands. GroceryLK compares live chocolate prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Single bars, sharing bags and gift boxes occupy different price tiers; family bars and bags give the best value per gram.',
      'Compare per-100g prices, as bar weights differ widely across brands.',
    ],
  },
  {
    slug: 'saree-price-sri-lanka',
    query: 'saree',
    name: 'Saree',
    title: 'Saree Price in Sri Lanka — Buy Online at the Best Price',
    desc: 'Compare saree prices in Sri Lanka. Find party wear, cotton, silk and trendy sarees online at the best price across Kapruka, Cargills, SPAR and more.',
    category: 'fashion',
    size: 'per saree',
    body: [
      'Sarees are a significant fashion purchase in Sri Lanka, and prices vary hugely by fabric, brand and occasion. GroceryLK compares live saree prices from online sellers so you can find a good price without bargaining.',
      'Cotton sarees are the most affordable everyday option, while silk and party-wear sarees command premium prices. Runner, plain, printed and traditional designs all sit in different price bands.',
      'Online saree prices are easy to compare because the same design is often listed by several sellers. Use the comparison below to see current prices side by side before you buy.',
    ],
  },
  {
    slug: 'fruits-price-sri-lanka',
    query: 'fruits',
    name: 'Fruits',
    title: 'Fruit Price in Sri Lanka — Per Kg by Store',
    desc: 'Compare fruit prices in Sri Lanka. See live prices for apples, bananas, oranges and more across Cargills, Kapruka, SPAR, Glomark & Arpico.',
    category: 'fruits',
    size: 'per kg',
    body: [
      'Fresh fruit is a daily part of the Sri Lankan diet, and prices swing with supply and season. GroceryLK compares live fruit prices across Cargills, Kapruka, SPAR, Glomark and Arpico.',
      'Bananas, papaya, pineapple and mango are local staples, while apples and oranges are imported and cost more. Prices are quoted per kilogram at most supermarkets.',
      'Imported fruit prices follow the exchange rate and shipment schedules, so they can change quickly. The live comparison below reflects current prices across the major chains.',
    ],
  },
  {
    slug: 'cargills-prices-sri-lanka',
    query: 'cargills',
    name: 'Cargills Price List',
    title: 'Cargills Price List 2026 — Food City Live Prices',
    desc: 'See current Cargills Food City prices in Sri Lanka — rice, dhal, milk powder, eggs and more, compared live and updated daily at GroceryLK.',
    category: 'store',
    size: 'various',
    body: [
      'Cargills Food City is Sri Lanka\u2019s largest supermarket chain, and millions of households want to know the current Cargills prices before they shop. GroceryLK tracks Cargills prices live for all the staples people buy every week.',
      'This Cargills price list covers rice, dhal, milk powder, eggs, sugar, cooking oil, bread, chicken and more, with prices captured directly from the Food City online store. Prices move with promotions, stock and the broader market.',
      'Because Cargills runs frequent promotions, a price checked today may differ next week. Bookmark this page and check back for the current Cargills price list, or browse each item below for the full multi-store comparison.',
    ],
  },
  {
    slug: 'kapruka-prices-sri-lanka',
    query: 'kapruka',
    name: 'Kapruka Price List',
    title: 'Kapruka Price List 2026 — All Product Categories',
    desc: 'See current Kapruka prices in Sri Lanka — groceries, sarees, electronics and more, compared live and updated daily at GroceryLK.',
    category: 'store',
    size: 'various',
    body: [
      'Kapruka is Sri Lanka\u2019s largest online shopping site, growing far beyond groceries into fashion, sarees, electronics and more. GroceryLK tracks live Kapruka prices so online shoppers can see real numbers before ordering.',
      'Kapruka advertises steep discounts on many items, but the final price depends on the seller and coupon codes. Comparing the listed price against other stores helps you know when a Kapruka deal is genuinely good.',
      'Kapruka listings change frequently as products go on sale and back off sale. Check back often for the current Kapruka price list, and use the item pages below for detailed comparisons.',
    ],
  },
  {
    slug: 'supermarket-price-comparison-sri-lanka',
    query: 'supermarket',
    name: 'Supermarket Price Comparison',
    title: 'Supermarket Prices in Sri Lanka — Compare All Stores 2026',
    desc: 'Compare supermarket prices in Sri Lanka across Cargills, Kapruka, SPAR, Glomark, Arpico and GFC. See which store is cheapest for every grocery item.',
    category: 'store',
    size: 'various',
    body: [
      'Which supermarket in Sri Lanka is cheapest? The answer changes by item and by week, which is exactly why GroceryLK compares prices live across Cargills, Kapruka, SPAR, Glomark, Arpico and GFC.',
      'No single store is cheapest on everything. One chain may lead on rice while another wins on milk powder or household goods. Comparing per-item across stores is the reliable way to cut your monthly grocery bill.',
      'This page is the hub for the whole comparison: every grocery category is listed below with the live per-item prices from all six stores. Browse the category you shop most to see who is cheapest today.',
    ],
  },
]

// Category hubs — /category/:slug aggregate related products into a hub page.
export const CATEGORIES = {
  rice: { name: 'Rice', title: 'Rice Price in Sri Lanka — Compare All Stores', desc: 'All rice prices in Sri Lanka in one place: keeri samba, basmati, nadu and more, compared across Cargills, Kapruka, SPAR, Glomark & Arpico.' },
  lentils: { name: 'Dhal & Lentils', title: 'Dhal & Lentil Price in Sri Lanka — Compare All Stores', desc: 'Dhal (parippu), green gram and lentil prices in Sri Lanka compared across all major stores.' },
  dairy: { name: 'Dairy', title: 'Dairy Price in Sri Lanka — Milk, Eggs & More', desc: 'Milk powder, eggs, yogurt and dairy product prices in Sri Lanka compared across all major stores.' },
  vegetables: { name: 'Vegetables', title: 'Vegetable Price in Sri Lanka Today — Per 1kg', desc: 'Fresh vegetable prices in Sri Lanka compared per 1kg across Cargills, Kapruka, SPAR, Glomark & Arpico. Potato, tomato, onion and more.' },
  meat: { name: 'Meat, Chicken & Fish', title: 'Chicken, Meat & Fish Price in Sri Lanka — Per Kg', desc: 'Fresh chicken, meat, fish and canned protein prices in Sri Lanka compared per kg across all major stores.' },
  staples: { name: 'Cooking Staples', title: 'Cooking Staple Prices in Sri Lanka', desc: 'Sugar, rice, cooking oil and other kitchen staple prices in Sri Lanka compared across all stores.' },
  bakery: { name: 'Bakery & Bread', title: 'Bread & Bakery Prices in Sri Lanka', desc: 'Bread and bakery product prices in Sri Lanka compared across all major stores.' },
  snacks: { name: 'Snacks & Treats', title: 'Snack, Biscuit & Chocolate Prices in Sri Lanka', desc: 'Biscuits, noodles, chocolate and snack prices in Sri Lanka compared across all stores.' },
  beverages: { name: 'Tea & Beverages', title: 'Tea & Beverage Prices in Sri Lanka', desc: 'Tea, juice and beverage prices in Sri Lanka compared across all major stores.' },
  toiletries: { name: 'Soap & Toiletries', title: 'Soap & Toiletry Prices in Sri Lanka', desc: 'Soap, shampoo, toothpaste and toiletries prices in Sri Lanka compared across all stores.' },
  spices: { name: 'Spices & Masala', title: 'Spice & Masala Prices in Sri Lanka', desc: 'Chilli, masala, turmeric and spice prices in Sri Lanka compared across all major stores.' },
  household: { name: 'Household & Cleaning', title: 'Household & Cleaning Prices in Sri Lanka', desc: 'Detergent, toilet paper, batteries and household product prices in Sri Lanka compared across all stores.' },
  baby: { name: 'Baby & Diapers', title: 'Baby Product Prices in Sri Lanka', desc: 'Diapers, wipes and baby product prices in Sri Lanka compared across all major stores.' },
  fashion: { name: 'Fashion & Sarees', title: 'Saree & Fashion Prices in Sri Lanka', desc: 'Saree and fashion prices in Sri Lanka compared across online sellers.' },
  fruits: { name: 'Fruits', title: 'Fresh Fruit Prices in Sri Lanka — Per Kg', desc: 'Fresh fruit prices in Sri Lanka compared per kg across Cargills, Kapruka, SPAR, Glomark & Arpico. Bananas, apples, oranges and more.' },
  store: { name: 'Store Price Lists', title: 'Supermarket Price Lists in Sri Lanka', desc: 'Compare Cargills, Kapruka, SPAR, Glomark, Arpico and GFC price lists in Sri Lanka — live prices for every grocery item.' },
}

// Store sub-pages: /p/:slug/:store for store-specific queries.
// slug (must match a SEO_PAGES slug): [store ids matching STORE_META]
export const STORE_SUBPAGES = {
  'rice-price-sri-lanka': ['cargills', 'kapruka', 'spar', 'glomark', 'arpico'],
  'milk-powder-price-sri-lanka': ['cargills', 'kapruka', 'spar'],
  'cooking-oil-price-sri-lanka': ['cargills', 'kapruka'],
  'eggs-price-sri-lanka': ['cargills', 'kapruka'],
  'potato-price-sri-lanka': ['cargills', 'kapruka'],
  'tea-price-sri-lanka': ['cargills', 'kapruka', 'spar'],
}

// STORE_META is defined inline in server.js currently; this export informs sitemap generation.
export const STORE_META = {
  kapruka: { name: 'Kapruka', url: 'https://www.kapruka.com/' },
  cargills: { name: 'Cargills', url: 'https://www.cargillsfoodcity.com/' },
  spar: { name: 'SPAR', url: 'https://spar2u.lk/' },
  glomark: { name: 'Glomark', url: 'https://glomark.lk/' },
  arpico: { name: 'Arpico', url: 'https://www.myarpico.com/' },
  gfc: { name: 'Global Food City', url: 'https://globalfoodcity.com/' },
}

// Sinhala localized pages — /si/:slug
export const SI_PAGES = {
  'rice-price-sri-lanka': { name: 'සහල් මිල', query: 'rice', title: 'සහල් මිල ශ්\u200dරී ලංකාවේ — සියලුම සාප්පු සසඳන්න', desc: 'ශ්\u200dරී ලංකාවේ සහල් මිල Cargills, Kapruka, SPAR, Glomark සහ Arpico හරහා සසඳන්න.' },
  'dhal-price-sri-lanka': { name: 'පරිප්පු මිල', query: 'dhal', title: 'පරිප්පු මිල ශ්\u200dරී ලංකාවේ', desc: 'ශ්\u200dරී ලංකාවේ පරිප්පු මිල සියලුම සාප්පු හරහා සසඳන්න.' },
  'milk-powder-price-sri-lanka': { name: 'කිරිපිටි මිල', query: 'milk powder', title: 'කිරිපිටි මිල ශ්\u200dරී ලංකාවේ', desc: 'කිරිපිටි මිල Anchor, Ratthi සහ අනෙකුත් වෙළඳ නාම සඳහා සසඳන්න.' },
  'eggs-price-sri-lanka': { name: 'බිත්තර මිල', query: 'eggs', title: 'බිත්තර මිල ශ්\u200dරී ලංකාවේ — ලාභම සාප්පුව', desc: 'බිත්තර මිල ලාභම සාප්පුව සොයා සසඳන්න.' },
  'sugar-price-sri-lanka': { name: 'සීනි මිල', query: 'sugar', title: 'සීනි මිල ශ්\u200dරී ලංකාවේ', desc: 'සීනි මිල සියලුම සාප්පු හරහා සසඳන්න.' },
  'cooking-oil-price-sri-lanka': { name: 'ඉවුම් පිහුම් තෙල් මිල', query: 'cooking oil', title: 'ඉවුම් පිහුම් තෙල් මිල ශ්\u200dරී ලංකාවේ', desc: 'පොල් තෙල්, එළවළු තෙල් මිල සසඳන්න.' },
}